
name: Upload Python Package To PyPi

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]'

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    environment:
      name: pypi
      url: https://pypi.org/p/BeatPrints

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.4.1
        with:
          virtualenvs-create: false

      - name: Run Black
        run: |
          poetry add black
          poetry run black .

        # Continue even if Black finds unformatted code
        continue-on-error: true 

      - name: Poetry build
        run: |
          poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
